services:
  backend:
    build:
      context: ./../
    image: {my_app}:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    container_name: {my_app}_service
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"

  postgres:
    image: postgres:16-alpine
    restart: always
    user: "70:70"
    volumes:
      - {my_app}_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5431:5432"
    container_name: {my_app}_service_postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

volumes:
  {my_app}_postgres_data: {}